name: Sync Assigned Issues to Board Workspace

on:
  schedule:
    - cron: "0 * * * *" # Ejecutar cada hora
  workflow_dispatch: # Ejecutar manualmente

jobs:
  sync_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Get repositories where the user is a collaborator or owner
        run: |
          repos=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/users/vicenteroa/repos?type=all" | jq -r '.[].full_name')
          echo "Repos: $repos"
          echo "::set-output name=repos::$repos"

      - name: Get issues assigned to user in all repos
        run: |
          repos="${{ steps.sync_issues.outputs.repos }}"
          issues=()
          for repo in $repos; do
            issues+=($(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          "https://api.github.com/repos/$repo/issues?state=open&assignee=vicenteroa" | \
                          jq -r '.[].id'))
          done
          echo "Issues: $issues"
          echo "::set-output name=issues::$issues"

      - name: Add issues to GitHub Project (Board Workspace)
        run: |
          project_id="PVT_kwHOBMPz284AuSzy"  # ID de tu Board Workspace
          issues="${{ steps.sync_issues.outputs.issues }}"
          for issue_id in $issues; do
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d '{"content_type": "Issue", "content_id": '"$issue_id"', "project_id": '"$project_id"'}' \
              https://api.github.com/repos/vicenteroa/REPO_NAME/projects/columns/cards
          done
